image:
  file: .gitpod.Dockerfile
tasks:
  - git clone https://github.com/behrica/doom.d.git /home/gitpod/.doom.d/
  - ~/.emacs.d/bin/doom -y sync

vscode:
  extensions:
    - ms-azuretools.vscode-docker
